### ISSUE TITLE
`polkadot-launch` npm package does not work

### ISSUE THREAD

**Issue by NachoPal** [paritytech/polkadot-launch#188]
For version `2.2.0`

```
yarn global add polkadot-launch

polkadot-launch config.json
```

```
...
Starting Relaychain Node dave... wsPort: 9903 rpcPort: undefined port: 30777 nodeKey: ce12849c8d20f93e0467b50e84a896ff675463842df0fcc226dbeaaa92693748
2022-06-03 14:40:29          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:32          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:34          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:37          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:39          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:42          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:44          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:47          API-WS: disconnected from ws://127.0.0.1:9900: 1006:: connection failed
2022-06-03 14:40:50        API/INIT: RPC methods not decorated: beefy_getFinalizedHead, mmr_generateBatchProof, state_trieMigrationStatus
2022-06-03 14:40:50        API/INIT: Error: FATAL: Unable to initialize the API: createType(StorageEntryTypeLatest):: Invalid character
    at EventEmitter.value (/Users/nacho/.config/yarn/global/node_modules/polkadot-launch/node_modules/@polkadot/api/base/Init.cjs:86:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

It works if used from the repo, though.

I noticed the `@polakdot/api` version is using is quite old. Maybe an upgrade would be something good to do.

**Comment by shawntabrizi** [comment]
@NachoPal does master work?

**Comment by NachoPal** [comment]
> @NachoPal does master work?

Yes, I updated the issue description

**Comment by bernardoaraujor** [comment]
when using master I can get it to start, but parachains won't produce blocks.

**Comment by skyao2002** [comment]
Bump, I'm using master and it doesn't even start, same error as above:

```
2022-06-20 21:25:27          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-20 21:25:30          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-20 21:25:32          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-20 21:25:35          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-20 21:25:38          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-20 21:25:41        API/INIT: RPC methods not decorated: beefy_getFinalizedHead, mmr_generateBatchProof, state_trieMigrationStatus
Starting a Collator for parachain 200: 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop, Collator port : 31200 wsPort : 9988 rpcPort : undefined
Added --alice
Added --force-authoring
Added  to parachain
Added --execution=wasm to collator

Killing all processes...
/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/create/createType.cjs:75
    firstError = new Error(`createType(${type}):: ${error.message}`);
                 ^

Error: createType(StorageEntryTypeLatest):: Invalid character
    at createTypeUnsafe (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/create/createType.cjs:75:18)
    at TypeRegistry.createTypeUnsafe (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/create/registry.cjs:417:45)
    at TypeRegistry.createType (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/create/registry.cjs:409:17)
    at extendHeadMeta (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:166:20)
    at extendPrefixedMap (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:186:23)
    at createFunction (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/metadata/decorate/storage/createFunction.cjs:224:5)
    at /Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/types/metadata/decorate/storage/index.cjs:59:60
    at Object.get [as account] (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/util/lazy.cjs:29:17)
    at /Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/api/base/Decorate.cjs:479:247
    at Object.get [as account] (/Users/stevenyao/.nvm/versions/node/v16.14.2/lib/node_modules/polkadot-launch/node_modules/@polkadot/util/lazy.cjs:29:17)
```

**Comment by shawntabrizi** [comment]
I just pushed again and it works for me locally:

```
➜  polkadot-launch git:(master) polkadot-launch --version
2.2.1
➜  polkadot-launch git:(master) polkadot-launch configLocal.json 

🧹 Resolving parachain id...
2022-06-21 01:49:43 Building chain spec    

🧹 Starting with a fresh authority set...
  👤 Added Genesis Authority alice
  👤 Added Genesis Authority bob
  👤 Added Genesis Authority charlie
  👤 Added Genesis Authority dave

⚙ Updating Relay Chain Genesis Configuration
  ⚠ Bad Genesis Configuration [ validation_upgrade_frequency: 10 ]
  ✓ Updated Genesis Configuration [ validation_upgrade_delay: 10 ]

⛓ Adding Genesis Parachains
  ✓ Added Genesis Parachain 200
  ✓ Added Genesis Parachain 300
⛓ Adding Genesis HRMP Channels
  ✓ Added HRMP channel 200 -> 300
Added Boot Nodes: /ip4/127.0.0.1/tcp/30444/p2p/12D3KooWABo9mUKBUAR8B8ovNtoQAFjjgC7SQqXDDgbQo1QYvG9L,/ip4/127.0.0.1/tcp/30555/p2p/12D3KooWK6f7zWCyor3JxrXeJUt9i68Df4SoEDVRAcbx7ZcHvKcr,/ip4/127.0.0.1/tcp/30666/p2p/12D3KooWDjt5wa7S3Gwn1HYz6zs288H9XnAfqB88VZmLDGnB7EU2,/ip4/127.0.0.1/tcp/30777/p2p/12D3KooWB4jq8GN4kuoKGEw1mePzxAAaDc8KHqGQFAd64g5DVEii

2022-06-21 01:49:44 Building chain spec    
2022-06-21 01:49:45 Took active validators from set with wrong size    
2022-06-21 01:49:45 Took active validators from set with wrong size.    
2022-06-21 01:49:45 Took active validators from set with wrong size    
Starting Relaychain Node alice... wsPort: 9944 rpcPort: 9844 port: 30444 nodeKey: 2fd2d13b106aa00faee3d042066fe08435b7fde1ba328d5ef682a3724597a752
Starting Relaychain Node bob... wsPort: 9955 rpcPort: 9855 port: 30555 nodeKey: c3a5b291253106bbb147dde37be0c27b8f7c3dacedf1ff83fb953f857f8d6025
Starting Relaychain Node charlie... wsPort: 9966 rpcPort: 9866 port: 30666 nodeKey: d6d1e70364e59496db666da48df421878875b7d6e5f76b4a6b35f7867c505437
Starting Relaychain Node dave... wsPort: 9977 rpcPort: 9877 port: 30777 nodeKey: cad05e45df579f90b7f96c191217e07034605795edd14f30dc4237f32b4b6956
2022-06-21 01:49:45          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:49:48          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:49:50          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:49:53          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:49:55        API/INIT: RPC methods not decorated: beefy_getFinalizedHead
Starting a Collator for parachain 200: 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop, Collator port : 31200 wsPort : 9988 rpcPort : 9888
Added --rpc-port=" + 9888
Added --alice
Added --force-authoring
Added  to parachain
Added --execution=wasm to collator
```

Can you all check again with 2.2.1?

**Comment by shawntabrizi** [comment]
I dont know what is going on here. It works locally for me:

```
yarn run v1.22.19
$ yarn build && node dist/cli.js configLocal.json
$ tsc

🧹 Resolving parachain id...
2022-06-21 01:54:33 Building chain spec    

🧹 Starting with a fresh authority set...
  👤 Added Genesis Authority alice
  👤 Added Genesis Authority bob
  👤 Added Genesis Authority charlie
  👤 Added Genesis Authority dave

⚙ Updating Relay Chain Genesis Configuration
  ⚠ Bad Genesis Configuration [ validation_upgrade_frequency: 10 ]
  ✓ Updated Genesis Configuration [ validation_upgrade_delay: 10 ]

⛓ Adding Genesis Parachains
  ✓ Added Genesis Parachain 200
  ✓ Added Genesis Parachain 300
⛓ Adding Genesis HRMP Channels
  ✓ Added HRMP channel 200 -> 300
Added Boot Nodes: /ip4/127.0.0.1/tcp/30444/p2p/12D3KooWPd6rpeRQw5o8ZxXagjQBXo7sTwQRjvktY1e8qPW164Rs,/ip4/127.0.0.1/tcp/30555/p2p/12D3KooWKy2LdXhsApScHNj2U5TFtWxmGU9DYQfR84F1DhZuo6Gc,/ip4/127.0.0.1/tcp/30666/p2p/12D3KooWJ9owWfPNZdLVyomp62ek6UjNBxwLHgJ2aSCio6y6n8re,/ip4/127.0.0.1/tcp/30777/p2p/12D3KooWQ3tEfZBYyLLLHHmSiw9o6U6mYLHUN8u4AunE57FD2MsD

2022-06-21 01:54:33 Building chain spec    
2022-06-21 01:54:35 Took active validators from set with wrong size    
2022-06-21 01:54:35 Took active validators from set with wrong size.    
2022-06-21 01:54:35 Took active validators from set with wrong size    
Starting Relaychain Node alice... wsPort: 9944 rpcPort: 9844 port: 30444 nodeKey: 09904596d5b68538a7e47db8b057a54916d72cf1e9594cd1730ce8838e91be48
Starting Relaychain Node bob... wsPort: 9955 rpcPort: 9855 port: 30555 nodeKey: 37c62796189e4d982ab11c19eddc16244eb4fb1598c4cb33256112a17970de02
Starting Relaychain Node charlie... wsPort: 9966 rpcPort: 9866 port: 30666 nodeKey: a90aea33d3716916f78d12478d42970b30ec920311e0403d24134a688a82500c
Starting Relaychain Node dave... wsPort: 9977 rpcPort: 9877 port: 30777 nodeKey: b37925fad359d1bfbc32a2fecd64f97b20207a78f387a931daa7dfa57fe65424
2022-06-21 01:54:35          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:54:37          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:54:40          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:54:42          API-WS: disconnected from ws://127.0.0.1:9944: 1006:: connection failed
2022-06-21 01:54:45        REGISTRY: Unknown signed extensions CheckNonZeroSender found, treating them as no-effect
2022-06-21 01:54:45        API/INIT: RPC methods not decorated: beefy_getFinalizedHead
Starting a Collator for parachain 200: 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop, Collator port : 31200 wsPort : 9988 rpcPort : 9888
Added --rpc-port=" + 9888
Added --alice
Added --force-authoring
Added  to parachain
Added --execution=wasm to collator
--- Submitting extrinsic to set balance of 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop to 1000000000000000000000. (nonce: 0) ---
Current status is Ready
Current status is {"broadcast":["12D3KooWQ3tEfZBYyLLLHHmSiw9o6U6mYLHUN8u4AunE57FD2MsD","12D3KooWJ9owWfPNZdLVyomp62ek6UjNBxwLHgJ2aSCio6y6n8re","12D3KooWKy2LdXhsApScHNj2U5TFtWxmGU9DYQfR84F1DhZuo6Gc","12D3KooWCrGW8HwkiQLmLN6XCmDWEMze9EFGkLwwBNiR2RuaVAFd"]}
Current status is {"inBlock":"0x2b30213d3b9462e9c1c376f18b913213c1d9414fff0479180f4be26c3cc8c513"}
Transaction included at blockHash 0x2b30213d3b9462e9c1c376f18b913213c1d9414fff0479180f4be26c3cc8c513
Starting a Collator for parachain 300: 5Ec4AhNv5ArwGxtngtW8qcVgzpCAu8nokvnh6vhtvvFkJtpq, Collator port : 31300 wsPort : 9999 rpcPort : undefined
Added --alice
Added --force-authoring
Added  to parachain
Added --execution=wasm to collator
--- Submitting extrinsic to set balance of 5Ec4AhNv5ArwGxtngtW8qcVgzpCAu8nokvnh6vhtvvFkJtpq to 1000000000000000000000. (nonce: 1) ---
Current status is Ready
Current status is {"broadcast":["12D3KooWRUzYoVfFcRKs3KvTqnjRRFr85ruXE5VJkJDe5DqWXnc2","12D3KooWQ3tEfZBYyLLLHHmSiw9o6U6mYLHUN8u4AunE57FD2MsD","12D3KooWJ9owWfPNZdLVyomp62ek6UjNBxwLHgJ2aSCio6y6n8re","12D3KooWKy2LdXhsApScHNj2U5TFtWxmGU9DYQfR84F1DhZuo6Gc","12D3KooWCrGW8HwkiQLmLN6XCmDWEMze9EFGkLwwBNiR2RuaVAFd"]}
Current status is {"inBlock":"0xf56cda693c73a89c8a09264db2cc317bd39f54805eae331975dacdd65ab4eabb"}
Transaction included at blockHash 0xf56cda693c73a89c8a09264db2cc317bd39f54805eae331975dacdd65ab4eabb
🚀 POLKADOT LAUNCH COMPLETE 🚀
```

But I get the same error when installing the package via NPM

**Comment by shawntabrizi** [comment]
Latest release 2.3.0 should work
