### ISSUE TITLE
Better support unhandled promise rejections

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot-launch#38]
Depending the version of Node, unhandled promises rejections exit the program.
It seems some part of the program is not handling some promises correctly

I am using node 15.5.

After putting an handler (in index.js):
```
process.on('unhandledRejection', error => {
	console.log('unhandledRejection', error.message);
	console.trace(error);
});

```

here is the log:
```
unhandledRejection undefined
Trace: _Event {
  type: 'error',
  isTrusted: false,
  _yaeti: true,
  target: W3CWebSocket {
    _listeners: {},
    addEventListener: [Function: _addEventListener],
    removeEventListener: [Function: _removeEventListener],
    dispatchEvent: [Function: _dispatchEvent],
    _url: 'ws://127.0.0.1:14944',
    _readyState: 3,
    _protocol: undefined,
    _extensions: '',
    _bufferedAmount: 0,
    _binaryType: 'arraybuffer',
    _connection: undefined,
    _client: WebSocketClient {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      config: [Object],
      _req: null,
      protocols: [],
      origin: undefined,
      url: [Url],
      secure: false,
      base64nonce: 'nEfONKqYabTY70pR3QGz/A==',
      [Symbol(kCapture)]: false
    },
    onclose: [Function: value],
    onerror: [Function: value],
    onmessage: [Function: value],
    onopen: [Function: value]
  },
  cancelable: true,
  stopImmediatePropagation: [Function (anonymous)]
}
    at process.<anonymous> (/projects/polkadot-launch/dist/index.js:34:11)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
2021-01-03 03:58:21          API-WS: disconnected from ws://127.0.0.1:14944
```

It seems to be related to yaeti (I'm not familiar with) and websocket.

**Comment by crystalin** [comment]
Also another error that appears a bit later:
```

Starting Parachain 200: 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop, Collator port : 15335 wsPort : 15946 rpcPort : 15846
Added  to parachain
Added --execution=wasm to collator
Registering Parachain 200
--- Submitting extrinsic to register parachain 200. (nonce: 0) ---
--- Submitting extrinsic to set balance of 5Ec4AhPTL6nWnUnw58QzjJvFd3QATwHA3UJnvSD4GVSQ7Gop to 1000000000000000000000. (nonce: 1) ---
Current status is Ready
unhandledRejection undefined is not iterable (cannot read property Symbol(Symbol.iterator))
Trace: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at _createForOfIteratorHelper (/home/alan/projects/polkadot-launch/dist/index.js:20:104)
    at _callee$ (/home/alan/projects/polkadot-launch/dist/index.js:261:26)
    at tryCatch (/home/alan/projects/polkadot-launch/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/alan/projects/polkadot-launch/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/alan/projects/polkadot-launch/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/alan/projects/polkadot-launch/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/alan/projects/polkadot-launch/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at process.<anonymous> (/home/alan/projects/polkadot-launch/dist/index.js:34:11)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)

```

**Comment by joelamouche** [comment]
The second error is due to the config not having a "simpleParachains" field, as added recently (https://github.com/paritytech/polkadot-launch/pull/25). Btw, we should have a talk about what this adder-collator is
